spring:
  # === ?????? ?? ?? ===
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 'umc9th2' ??????? ?????. MySQL Workbench?? ?? ??????!
    url: jdbc:mysql://localhost:3306/umc9th2?serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password: ssms101504@ # ? ??? ?? ????? ?????!

  # === JPA(?????? ??? ??) ?? ===
  jpa:
    hibernate:
      # ? ?? ??? ?? ??? ?? DB ???? ???? ??????.
      ddl-auto: create
    properties:
      hibernate:
        # ???? SQL ??? ??? ? ? ?? ??? ?????.
        show_sql: true
        format_sql: true
jwt:
  secret: "vmfhalstkfkdgodyqksghkrdltdmsqkdghkrdltdmsqkdghkrdltdmsqkdghkrdltdmsqkdghkrdltdms"
  # 👆 32글자 이상 아무 문자열이나 아주 길게 입력하세요! (Base64 인코딩 권장하지만 일단 문자열로)