spring:
  application:
    name: "demo" # "umc9th"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL JDBC ???? ??? ??
    url: jdbc:mysql://localhost:3306/springboot_db # jdbc:mysql://localhost:3306/{???????}
    username: root # MySQL ?? ??
    password: 050626aa!! # MySQL ????

  jpa:
    database: mysql # ??? ?????? ?? ?? (MySQL)
    database-platform: org.hibernate.dialect.MySQLDialect # Hibernate?? ??? MySQL ??(dialect) ??
    show-sql: true # ??? SQL ??? ??? ???? ?? ??
    hibernate:
      ddl-auto: update # ?????? ?? ? ?????? ???? ??? ??
    properties:
      hibernate:
        format_sql: true # ???? SQL ??? ?? ?? ???