spring:
  # === ?????? ?? ?? ===
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 'umc9th2' ??????? ?????. MySQL Workbench?? ?? ??????!
    url: jdbc:mysql://localhost:3306/umc9th2?serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password: ssms101504@ # ? ??? ?? ????? ?????!

  # === JPA(?????? ??? ??) ?? ===
  jpa:
    hibernate:
      # ? ?? ??? ?? ??? ?? DB ???? ???? ??????.
      ddl-auto: create
    properties:
      hibernate:
        # ???? SQL ??? ??? ? ? ?? ??? ?????.
        show_sql: true
        format_sql: true